server:
  port: 9001

spring:
  cloud:
    consul:
      config:
        fail-fast: true
      host: config-server
      port: 8500
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  application:
    name: service-registry
  config:
    import: "optional:consul:"