version: '3.8'

services:

  db:
    image: 'postgres:alpine3.19'
    container_name: db
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=chous
      - POSTGRES_PASSWORD=chous
      - POSTGRES_DB=bookshelf
    networks:
      - bookshelf-docker-network

  mongo:
    image: 'mongo:latest'
    container_name: mongo
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chous
      - MONGO_INITDB_ROOT_PASSWORD=chous
      - MONGO_INITDB_DATABASE=bookshelf
    volumes:
      - ./image-service/src/main/resources/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - bookshelf-docker-network

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    expose:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - bookshelf-docker-network

  kafka:
    image: 'bitnami/kafka:latest'
    user: root
    expose:
      - "9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - bookshelf-docker-network
    depends_on:
      - zookeeper

  config-server:
    image: 'config-server:latest'
    build:
      context: /config-server
      dockerfile: Dockerfile
    expose:
      - "8088"
    networks:
      - bookshelf-docker-network
    healthcheck:
      test: [ "CMD-SHELL", " netstat -an | grep -q 8088" ]

  api-gateway:
    image: 'api-gateway:latest'
    build:
      context: /api-gateway
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    networks:
      - bookshelf-docker-network
    depends_on:
      config-server:
        condition: service_healthy

  book-service:
    image: 'book-service:latest'
    build:
      context: /book-service
      dockerfile: Dockerfile
    expose:
      - "8081"
    networks:
      - bookshelf-docker-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bookshelf
      - SPRING_DATASOURCE_USERNAME=chous
      - SPRING_DATASOURCE_PASSWORD=chous
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      kafka:
        condition: service_started
      config-server:
        condition: service_healthy

  image-service:
    image: 'image-service:latest'
    build:
      context: /image-service
      dockerfile: Dockerfile
    expose:
      - "8082"
    networks:
      - bookshelf-docker-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongo://mongo:27017/bookshelf
      - SPRING_DATASOURCE_USERNAME=chous
      - SPRING_DATASOURCE_PASSWORD=chous
    depends_on:
      kafka:
        condition: service_started
      config-server:
        condition: service_healthy

  consul:
    image: 'consul:1.15.4'
    ports:
      - "8500:8500"
    networks:
      - bookshelf-docker-network

networks:
  bookshelf-docker-network:
    driver: bridge