server:
  global:
    scrape_interval: 15s # Specifies the time interval at which Prometheus will scrape and collect metrics from the configured targets
  alerting:
    alertmanagers:
      - scheme: http
        static_configs:
          - targets:
              - alertmanager:9093
  scrape_configs:
    - job_name: 'prometheus'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: ['localhost:9090'] # Prometheus should scrape metrics from the instance running and listening on port `9090`