server:
  global:
    scrape_interval: 10s
  scrape_configs:
    - job_name: 'prometheus'
      metrics_path: /actuator/prometheus
      scrape_interval: 3s
      static_configs:
        - targets: ['book-service.default.svc:8081']
#        - targets: ['book-service.default.svc.cluster.local:8081']