spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-server:8088"
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/api/v1/books-image/**
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}