spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/books/**
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/api/v1/books-image/**