spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshelf
    username: chous
    password: chous
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
